language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:

script:
    - echo 'foo'

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app : mytotoproject
    skip_cleanup: True